@startuml

!define C4Container https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
!include C4Container

skinparam svgLinkTarget foo

System_Boundary(c1, "edx-platform: eol-edx", $link="https://github.com/eol-uchile/eol-edx") {
    System_Boundary(c2, "requirements", $link="https://github.com/eol-uchile/eol-edx/blob/eol-release/koa/requirements/") {
        
            System_Boundary(apis, "apis", $link="https://github.com/eol-uchile/eol-edx/blob/eol-release/koa/requirements/apis.txt") {
            
                Container(apis1, "eol_api", $link="https://github.com/eol-uchile/eol-api/releases/tag/1.2.0+l")
            
            }
        
            System_Boundary(apps, "apps", $link="https://github.com/eol-uchile/eol-edx/blob/eol-release/koa/requirements/apps.txt") {
            
                Container(apps1, "edx-proctoring", $link="https://github.com/openedx/edx-proctoring/releases/tag/2.6.7")
            
                Container(apps2, "course_classification", $link="https://github.com/eol-uchile/course_classification/releases/tag/1.6.1+l")
            
                Container(apps3, "edxucursos", $link="https://github.com/eol-uchile/edx-ucursos/releases/tag/3.1.0+l")
            
                Container(apps4, "eol_certificates", $link="https://github.com/eol-uchile/eol-certificates/releases/tag/0.2.0+l")
            
                Container(apps5, "eol_contact_form", $link="https://github.com/eol-uchile/eol_contact_form/releases/tag/0.5.3+l")
            
                Container(apps6, "eol_duplicate_xblock", $link="https://github.com/eol-uchile/eol_duplicate_xblock/releases/tag/1.0.0+l")
            
                Container(apps7, "eol_jump_to", $link="https://github.com/eol-uchile/eol_jump_to/releases/tag/0.0.1")
            
                Container(apps8, "eol_survey", $link="https://github.com/eol-uchile/eol_survey/releases/tag/3.2.1+l")
            
                Container(apps9, "eol_vimeo", $link="https://github.com/eol-uchile/eol_vimeo/releases/tag/1.0.1+l")
            
                Container(apps10, "uchileedxlogin", $link="https://github.com/eol-uchile/uchileedxlogin/releases/tag/2.0.2+l")
            
            }
        
            System_Boundary(python_packages, "python_packages", $link="https://github.com/eol-uchile/eol-edx/blob/eol-release/koa/requirements/python_packages.txt") {
            
                Container(python_packages1, "django-redis")
            
                Container(python_packages2, "edx-username-changer", $link="https://github.com/mitodl/edx-username-changer.git/releases/tag/main")
            
                Container(python_packages3, "fluent-logger")
            
                Container(python_packages4, "python-json-logger")
            
            }
        
            System_Boundary(reports, "reports", $link="https://github.com/eol-uchile/eol-edx/blob/eol-release/koa/requirements/reports.txt") {
            
                Container(reports1, "cmmedu_seguimiento", $link="https://github.com/cmmedu/cmmedu-seguimiento/releases/tag/v1.2.1")
            
                Container(reports2, "gradeucursos", $link="https://github.com/eol-uchile/eol_grade_ucursos/releases/tag/3.0.0+l")
            
                Container(reports3, "eol_report_analytics", $link="https://github.com/eol-uchile/eol_report_analytics/releases/tag/2.1.0+l")
            
                Container(reports4, "xblockcompletion", $link="https://github.com/eol-uchile/eol_xblock_completion/releases/tag/1.1.0+l")
            
            }
        
            System_Boundary(tabs_plugins, "tabs_plugins", $link="https://github.com/eol-uchile/eol-edx/blob/eol-release/koa/requirements/tabs_plugins.txt") {
            
                Container(tabs_plugins1, "eol_completion", $link="https://github.com/eol-uchile/eol_completion/releases/tag/2.1.1+l")
            
                Container(tabs_plugins2, "eol_course_email", $link="https://github.com/eol-uchile/eol_course_email/releases/tag/0.0.1+l")
            
                Container(tabs_plugins3, "eol_feedback", $link="https://github.com/eol-uchile/eol_feedback/releases/tag/0.0.3+l")
            
                Container(tabs_plugins4, "eol_progress_tab", $link="https://github.com/eol-uchile/eol_progress_tab/releases/tag/0.0.1+l")
            
                Container(tabs_plugins5, "welcome_mail", $link="https://github.com/eol-uchile/eol_welcome_mail/releases/tag/0.0.1+l")
            
            }
        
            System_Boundary(xblocks, "xblocks", $link="https://github.com/eol-uchile/eol-edx/blob/eol-release/koa/requirements/xblocks.txt") {
            
                Container(xblocks1, "iterativexblock", $link="https://github.com/cmmedu/iterative-xblock/releases/tag/v1.0.5")
            
                Container(xblocks2, "cmmedu-ordertable-xblock", $link="https://github.com/cmmedu/cmmedu-ordertable-xblock/releases/tag/v1.0.1")
            
                Container(xblocks3, "ora2", $link="https://github.com/eol-uchile/edx-ora2/commit/e873498bd2671b830f19a2441ec1608b7d4bbbc4")
            
                Container(xblocks4, "edx-sga", $link="https://github.com/eol-uchile/edx-sga/releases/tag/0.10.0+eol3.1.2")
            
                Container(xblocks5, "scormxblock-xblock", $link="https://github.com/eol-uchile/edx_xblock_scorm/releases/tag/0.5.1+l")
            
                Container(xblocks6, "eolconditional-xblock", $link="https://github.com/eol-uchile/eol-conditional-xblock/releases/tag/1.0.0+l")
            
                Container(xblocks7, "eolcontainer-xblock", $link="https://github.com/eol-uchile/eol-container-xblock/releases/tag/v1.2.0+l")
            
                Container(xblocks8, "eolcourseprogram-xblock", $link="https://github.com/eol-uchile/eol-course-program-xblock/releases/tag/0.2.0+l")
            
                Container(xblocks9, "dialogsquestionsxblock-xblock", $link="https://github.com/eol-uchile/eol-dialogs-question-xblock/releases/tag/v1.1.0+l")
            
                Container(xblocks10, "eoldialogs-xblock", $link="https://github.com/eol-uchile/eol-dialogs-xblock/releases/tag/1.0.0+l")
            
                Container(xblocks11, "eol_forum_notifications", $link="https://github.com/eol-uchile/eol_forum_notifications/releases/tag/1.0.4+l")
            
                Container(xblocks12, "eolgradediscussion", $link="https://github.com/eol-uchile/eol_gradeforum_xblock/releases/tag/1.0.0+l")
            
                Container(xblocks13, "img-annotation", $link="https://github.com/eol-uchile/eol_img_annotation/releases/tag/1.0.1+l")
            
                Container(xblocks14, "eollistgrade-xblock", $link="https://github.com/eol-uchile/eol_list_grade/releases/tag/1.0.0+l")
            
                Container(xblocks15, "eolpersistenttab-xblock", $link="https://github.com/eol-uchile/eol-persistent-tab-xblock/releases/tag/1.0.0+l")
            
                Container(xblocks16, "eolquestion-xblock", $link="https://github.com/eol-uchile/eol-question-xblock/releases/tag/v1.0.0+l")
            
                Container(xblocks17, "vof-xblock", $link="https://github.com/eol-uchile/eol-vof-xblock/releases/tag/v1.0.1+l")
            
                Container(xblocks18, "eoldiscussion-xblock", $link="https://github.com/eol-uchile/eol_xblock_discussion/releases/tag/1.3.1+l")
            
                Container(xblocks19, "eolzoom-xblock", $link="https://github.com/eol-uchile/eol-zoom-xblock/releases/tag/1.1.2+l")
            
                Container(xblocks20, "flow-control-xblock", $link="https://github.com/eduNEXT/flow-control-xblock/releases/tag/v1.0.1")
            
                Container(xblocks21, "xblock-free-text-response", $link="https://github.com/eol-uchile/free-text-response/releases/tag/0.4.1+l")
            
                Container(xblocks22, "pdf-xblock", $link="https://github.com/eol-uchile/pdfXBlock/releases/tag/v0.5.1+l")
            
                Container(xblocks23, "sence-xblock", $link="https://github.com/eol-uchile/sence-xblock/releases/tag/2.0.0+l")
            
                Container(xblocks24, "ubcpi-xblock", $link="https://github.com/eol-uchile/ubcpi/releases/tag/1.0.0")
            
                Container(xblocks25, "xblock-drag-and-drop-v2", $link="https://github.com/openedx/xblock-drag-and-drop-v2/releases/tag/v3.0.0")
            
                Container(xblocks26, "invideoquiz", $link="https://github.com/eol-uchile/xblock-in-video-quiz/releases/tag/1.1.0+l")
            
            }
        
    }

    System_Boundary(theme, "Themes", $link="https://github.com/eol-uchile/eol-edx/blob/eol-release/koa/themes/") {
        
            Container(theme1, "alpha-project-theme", $link="https://github.com/eol-uchile/alpha-project-theme")
        
            Container(theme2, "cmm-openedx", $link="https://github.com/eol-uchile/cmm-theme")
        
            Container(theme3, "eol-uchile-2020", $link="https://github.com/eol-uchile/eol-uchile-theme-2020")
        
            Container(theme4, "virtual-labx-theme", $link="https://github.com/eol-uchile/virtual-labx-theme.git")
        
    }

    System_Boundary(dockerfile, "edx-platform base", $link="https://github.com/eol-uchile/eol-edx/blob/eol-release/koa/Dockerfile") {
            Container(dk, "eol-koa-20260603133110", $link="https://ghcr.io/eol-uchile/edx-platform:eol-koa-20260603133110")
    }
}

SHOW_LEGEND()

@enduml