name: Update Image

on:
  repository_dispatch:
    types: [update-image]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write

    steps:
      - uses: actions/checkout@v4
        with:
          ref: '${{ github.event.client_payload.project }}-release/${{ github.event.client_payload.version }}'

      - name: Pull submodules
        run: git submodule update --init --recursive

      - name: Set current date as env variable
        run: echo "TS=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV

      - name: Build Open edX
        run: docker build . --file ./Dockerfile --tag ghcr.io/eol-uchile/eol-edx:${GITHUB_SHA} --tag ghcr.io/eol-uchile/eol-edx:${{ github.event.client_payload.version }} --tag ghcr.io/eol-uchile/eol-edx:${{ github.event.client_payload.version }}-${{ env.TS }} --target base

      - name: Build Static files for OpenedX S3
        run: docker build . --file ./Dockerfile --tag ghcr.io/eol-uchile/eol-edx:s3-static-${GITHUB_SHA} --tag ghcr.io/eol-uchile/eol-edx:s3-static-${{ github.event.client_payload.version }} --tag ghcr.io/eol-uchile/eol-edx:s3-static-${{ github.event.client_payload.version }}-${{ env.TS }} --target s3

      - name: Login to GitHub Container Registry
        if: github.ref == format('refs/heads/{0}-release/{1}', ${{ github.event.client_payload.project }}, ${{ github.event.client_payload.version }})
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push to GitHub Container Registry
        if: github.ref == format('refs/heads/{0}-release/{1}', ${{ github.event.client_payload.project }}, ${{ github.event.client_payload.version }})
        run: |
          docker push ghcr.io/eol-uchile/eol-edx:${GITHUB_SHA}
          docker push ghcr.io/eol-uchile/eol-edx:${{ github.event.client_payload.version }}
          docker push ghcr.io/eol-uchile/eol-edx:${{ github.event.client_payload.version }}-${{ env.TS }}
          docker push ghcr.io/eol-uchile/eol-edx:s3-static-${GITHUB_SHA}
          docker push ghcr.io/eol-uchile/eol-edx:s3-static-${{ github.event.client_payload.version }}
          docker push ghcr.io/eol-uchile/eol-edx:s3-static-${{ github.event.client_payload.version }}-${{ env.TS }}

  webhook:
    needs: [ build ]
    if: github.ref == format('refs/heads/{0}-release/{1}', ${{ github.event.client_payload.project }}, ${{ github.event.client_payload.version }})
    uses: ./.github/workflows/webhook.yml
    secrets: inherit
