name: Webhook Update staging

on:
  workflow_run:
    workflows: ["Docker Image CI"]
    types:
      - completed
  repository_dispatch:
    types: [debug-webhook]

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' || "${{ github.event.client_payload.debug }}" = "eol" }}
    steps:
      - name: Trigger second repository
        run: |
          curl --fail-with-body -X POST -H "Authorization: Bearer ${{ secrets.WEBHOOK_SECRET }}" -H "Accept: application/vnd.github.everest-preview+json" -H "Content-Type: application/json" https://api.github.com/repos/eol-uchile/edx-kustomize/dispatches --data '{"event_type": "update-images-v2", "client_payload": {"flavour": "eol"}}'
